version: '3.8'

services:
  backend:
    build: .
    container_name: studyguider_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/bookAdders/csv:/csv
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=mydb
      - DATABASE_USER=bruno
      - DATABASE_PASSWORD=your_password

  db:
    image: ankane/pgvector
    container_name: studyguider_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
