version: '3.8'

services:
  ollama:
    image: brunozeg/ollama-baked:llama3.1
    container_name: ollama
    # command: ["serve"]
    ports:
      - "11434:11434"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -I http://localhost:11434/"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    container_name: studyguider_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:

    build: .
    container_name: studyguider_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/bookAdders/csv:/csv
      - ./backend/images:/images
    depends_on:
      - db
      - ollama

    env_file:
      - .env

  db:
    image: ankane/pgvector
    container_name: studyguider_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
